### ISSUE TITLE
[1.18 & 1.19] HP issue after saving & loading when having Health Boost enchantment

### ISSUE THREAD

**Issue by SodiumZH** [Mechalopa/Hostile-Mobs-and-Girls#7]
If a player has the Health Boost enchantment and have HP>20 (10 hearts), after restarting the game (including returning to the main menu and load the world again), the HP will be reset to 20 instead of keeping the value before.

**Comment by P3rf3ctXZer0** [comment]
Which mods cause this doesn't happen with Spice of Life or Twilight Forest you can even check using my pack ``Fiction Friction`` I am also happy to op you. Did you add debugify which fixes a known vanilla bug? What about attribute fix? You need at least that for the game to stop resetting you too otherwise you will get a NaNHealth issue.

**Comment by Mechalopa** [comment]
OK, it's a vanilla bug. ([MC-17876](https://bugs.mojang.com/browse/MC-17876))
It can be fixed by installing [Max Health Fix](https://www.curseforge.com/minecraft/mc-mods/max-health-fix) by DarkhaxDev.
